# Generated by Django 2.0.5 on 2018-10-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseLocation',
            new_name='Apartment',
        ),
    ]
