# Generated by Django 2.1.2 on 2018-10-21 18:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0002_auto_20181021_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name_plural': 'Apartment'},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_carpet_area',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_floor_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_furnishing',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_maintainance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_overlooking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_tenants',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='super_buildup_area',
            field=models.IntegerField(null=True),
        ),
    ]
