# Generated by Django 2.1.2 on 2018-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_owner_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartmrnt_owner_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostels_owner_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostels_owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostels_owner_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houses',
            name='houses_owner_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='houses_owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='houses_owner_number',
            field=models.IntegerField(default=0),
        ),
    ]
