# Generated by Django 2.1.2 on 2018-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0008_auto_20181123_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='houses_owner_mail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
