# Generated by Django 2.1.2 on 2018-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0009_auto_20181123_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='hostel_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
