# Generated by Django 2.1.2 on 2018-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0010_hostels_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='house_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
