# Generated by Django 2.1.2 on 2018-11-25 20:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0011_houses_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='comments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
