# Generated by Django 2.1.2 on 2018-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0012_auto_20181125_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
