# Generated by Django 2.1.2 on 2018-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0013_auto_20181126_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
