# Generated by Django 2.1.2 on 2018-11-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0015_auto_20181126_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='imgages8',
            new_name='images8',
        ),
    ]
