# Generated by Django 2.1.2 on 2018-11-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0017_auto_20181128_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostels',
            old_name='apartment_description',
            new_name='hostel_description',
        ),
    ]
