# Generated by Django 2.1.2 on 2018-11-28 11:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0018_auto_20181128_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='hostel_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostels_owner_number',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
