# Generated by Django 2.1.2 on 2018-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0019_auto_20181128_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostels',
            old_name='hostels_owner_mail',
            new_name='hostel_owner_mail',
        ),
        migrations.RenameField(
            model_name='hostels',
            old_name='hostels_owner_name',
            new_name='hostel_owner_name',
        ),
        migrations.RenameField(
            model_name='hostels',
            old_name='hostels_owner_number',
            new_name='hostel_owner_number',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='houses_owner_mail',
            new_name='house_owner_mail',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='houses_owner_name',
            new_name='house_owner_name',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='houses_owner_number',
            new_name='house_owner_number',
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
