# Generated by Django 2.0.9 on 2018-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_renting_app', '0022_auto_20181129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
